### ISSUE TITLE
Moving a valve also moves the underlying node

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#78] opened 2015-11-12 08:32 UTC
Moving a valve from an intersection of two pipes also moves the node.
This means the pipes are referencing a node that may be 10 meters away from their location.
That node is also keeping the _pipe_node_type which it got when the pipes were first created, which shouldn't happen.

To replicate, just draw two pipes and a valve at the intersection and move the valve.

**Comment by 3nids** [comment] 2015-11-13 13:59
it's not quite easy to solve...
the problem is with the IDs.
Either the node or the moved network element (valve, installation, etc) should get a new ID. I would vote for keeping network element id (for maintenance events or whatever), create a new node and reassign the pipes. What do you think?

**Comment by tudorbarascu** [comment] 2015-11-13 18:17
+1 for "keeping network element id (for maintenance events or whatever), create a new node and reassign the pipes"
Thanks

**Comment by 3nids** [comment] 2015-11-27 14:15
this should be fixed now.
although, there is one remaining problem: we shouldn't allow nodes to be superposed. And right now, if you move a valve on an existing node, you'll get two nodes...

**Comment by sylvainbeo** [comment] 2017-03-17 09:42
Valves not anymore in nodes. I think this issue may be closed ?

**Comment by haubourg** [comment] 2017-03-28 12:35
fix confirmed, closing

**Closed by haubourg** 2017-03-28 12:35 UTC
